CREATE TABLE IF NOT EXISTS users (
	id UUID DEFAULT uuid_generate_v4(),
	firstname CHARACTER VARYING NOT NULL,
	lastname CHARACTER VARYING NOT NULL,
	middlename CHARACTER VARYING,
	email CHARACTER VARYING UNIQUE,
	created_at TIMESTAMP WITH TIME ZONE,
	modified_at TIMESTAMP WITH TIME ZONE,
	birthday TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS alias (
	user_id UUID NOT NULL,
	ally CHARACTER VARYING,
	PRIMARY KEY (ally),
	CONSTRAINT user_id_fk FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);


